-- Add immutable attendance events, attendance flags, and append-only flag review history.

CREATE TYPE event_type AS ENUM (
  'time_in',
  'lunch_out',
  'lunch_in',
  'time_out',
  'visit_in',
  'visit_out',
  'gps_ping'
);

CREATE TYPE validation_status AS ENUM (
  'normal',
  'warning',
  'flagged',
  'needs_review',
  'overtime_candidate'
);

CREATE TYPE flag_severity AS ENUM ('warning', 'high');
CREATE TYPE flag_review_workflow_mode AS ENUM (
  'manager_review_admin_observe',
  'manager_preapprove_admin_final',
  'manager_view_admin_approve'
);
CREATE TYPE flag_review_stage AS ENUM ('manager', 'admin');
CREATE TYPE flag_review_decision AS ENUM (
  'approved',
  'pre_approved',
  'rejected',
  'resolved'
);

INSERT INTO attendance_rules (
  rule_key,
  rule_value,
  value_type,
  description,
  effective_from,
  created_by
)
VALUES (
  'gps_low_accuracy_threshold_meters',
  '100'::jsonb,
  'integer',
  'GPS accuracy in meters above which an attendance event receives a gps_low_accuracy warning flag.',
  CURRENT_DATE,
  NULL
);

-- Direct authenticated session writes are already revoked. Keep the session
-- guard compatible with offline events captured before a later deactivation;
-- the event insert trigger below is the time-aware rejection point.
CREATE OR REPLACE FUNCTION require_active_consented_attendance_session_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM public.users
    WHERE id = NEW.user_id
      AND location_consent_given_at IS NOT NULL
      AND (active = true OR deactivated_at IS NOT NULL)
  ) THEN
    RAISE EXCEPTION 'Attendance sessions require a consented active account or a deactivated account with a recorded deactivation time.';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TABLE attendance_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  user_id uuid NOT NULL,
  client_event_id uuid NOT NULL,
  event_type event_type NOT NULL,
  captured_at_local timestamptz NOT NULL,
  received_at_server timestamptz NOT NULL DEFAULT now(),
  location_id uuid,
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  gps_accuracy_meters numeric(10, 2),
  gps_expires_at timestamptz NOT NULL,
  offline_declared boolean NOT NULL DEFAULT false,
  offline_evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  photo_path text,
  photo_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  photo_verified boolean NOT NULL DEFAULT false,
  validation_status validation_status NOT NULL DEFAULT 'normal',
  validation_evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT attendance_events_session_id_fkey
    FOREIGN KEY (session_id) REFERENCES attendance_sessions(id),
  CONSTRAINT attendance_events_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT attendance_events_location_id_fkey
    FOREIGN KEY (location_id) REFERENCES locations(id),
  CONSTRAINT attendance_events_user_client_event_unique
    UNIQUE (user_id, client_event_id),
  CONSTRAINT attendance_events_coordinates_pair_check CHECK (
    (latitude IS NULL AND longitude IS NULL)
    OR (latitude IS NOT NULL AND longitude IS NOT NULL)
  ),
  CONSTRAINT attendance_events_latitude_valid CHECK (
    latitude IS NULL OR latitude BETWEEN -90 AND 90
  ),
  CONSTRAINT attendance_events_longitude_valid CHECK (
    longitude IS NULL OR longitude BETWEEN -180 AND 180
  ),
  CONSTRAINT attendance_events_gps_accuracy_non_negative CHECK (
    gps_accuracy_meters IS NULL OR gps_accuracy_meters >= 0
  ),
  CONSTRAINT attendance_events_private_photo_path_check CHECK (
    photo_path IS NULL OR photo_path !~* '^https?://'
  ),
  CONSTRAINT attendance_events_offline_evidence_object_check CHECK (
    jsonb_typeof(offline_evidence) = 'object'
  ),
  CONSTRAINT attendance_events_photo_metadata_object_check CHECK (
    jsonb_typeof(photo_metadata) = 'object'
  ),
  CONSTRAINT attendance_events_validation_evidence_object_check CHECK (
    jsonb_typeof(validation_evidence) = 'object'
  )
);

COMMENT ON TABLE attendance_events IS
  'Append-only attendance evidence. received_at_server is generated by PostgreSQL; client capture time remains evidence. Private photo paths and precise GPS data require retention processing.';
COMMENT ON COLUMN attendance_events.photo_path IS
  'Private Supabase Storage object path only. Never store a public or permanent signed URL.';
COMMENT ON COLUMN attendance_events.offline_declared IS
  'Primary offline classification signal supplied by the client. Receipt delay is supporting evidence only.';

CREATE INDEX attendance_events_session_id_idx
ON attendance_events (session_id);
CREATE INDEX attendance_events_user_id_idx
ON attendance_events (user_id);
CREATE INDEX attendance_events_captured_at_local_idx
ON attendance_events (captured_at_local);
CREATE INDEX attendance_events_received_at_server_idx
ON attendance_events (received_at_server);

CREATE TABLE attendance_flags (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  attendance_event_id uuid,
  user_id uuid NOT NULL,
  flag_type flag_type NOT NULL,
  severity flag_severity NOT NULL,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  workflow_mode flag_review_workflow_mode NOT NULL,
  workflow_effective_from date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT attendance_flags_session_id_fkey
    FOREIGN KEY (session_id) REFERENCES attendance_sessions(id),
  CONSTRAINT attendance_flags_attendance_event_id_fkey
    FOREIGN KEY (attendance_event_id) REFERENCES attendance_events(id),
  CONSTRAINT attendance_flags_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT attendance_flags_evidence_object_check CHECK (
    jsonb_typeof(evidence) = 'object'
  )
);

COMMENT ON TABLE attendance_flags IS
  'Append-only evidence and workflow snapshots. Flags never block attendance capture and review outcomes are recorded only in attendance_flag_reviews.';

CREATE INDEX attendance_flags_session_id_idx
ON attendance_flags (session_id);
CREATE INDEX attendance_flags_attendance_event_id_idx
ON attendance_flags (attendance_event_id);
CREATE INDEX attendance_flags_user_id_idx
ON attendance_flags (user_id);
CREATE INDEX attendance_flags_type_created_at_idx
ON attendance_flags (flag_type, created_at DESC);

CREATE TABLE attendance_flag_reviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  attendance_flag_id uuid NOT NULL,
  actor_user_id uuid NOT NULL,
  stage flag_review_stage NOT NULL,
  decision flag_review_decision NOT NULL,
  remarks text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT attendance_flag_reviews_attendance_flag_id_fkey
    FOREIGN KEY (attendance_flag_id) REFERENCES attendance_flags(id),
  CONSTRAINT attendance_flag_reviews_actor_user_id_fkey
    FOREIGN KEY (actor_user_id) REFERENCES users(id),
  CONSTRAINT attendance_flag_reviews_remarks_required CHECK (
    length(btrim(remarks)) > 0
  )
);

COMMENT ON TABLE attendance_flag_reviews IS
  'Append-only review decision history. Current review state is derived from history; attendance flags are not overwritten by decisions.';

CREATE INDEX attendance_flag_reviews_flag_created_at_idx
ON attendance_flag_reviews (attendance_flag_id, created_at);
CREATE INDEX attendance_flag_reviews_actor_user_id_idx
ON attendance_flag_reviews (actor_user_id);

CREATE OR REPLACE FUNCTION validate_attendance_event_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  session_record public.attendance_sessions%ROWTYPE;
  account_record public.users%ROWTYPE;
BEGIN
  SELECT *
  INTO session_record
  FROM public.attendance_sessions
  WHERE id = NEW.session_id;

  IF NOT FOUND OR session_record.user_id IS DISTINCT FROM NEW.user_id THEN
    RAISE EXCEPTION 'Attendance event must belong to its session owner.';
  END IF;

  IF (session_record.session_type = 'stationary_day'
      AND NEW.event_type NOT IN ('time_in', 'lunch_out', 'lunch_in', 'time_out', 'gps_ping'))
    OR (session_record.session_type = 'field_visit'
      AND NEW.event_type NOT IN ('visit_in', 'visit_out', 'gps_ping'))
  THEN
    RAISE EXCEPTION 'Attendance event type is incompatible with the session type.';
  END IF;

  SELECT *
  INTO account_record
  FROM public.users
  WHERE id = NEW.user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Attendance event user must exist.';
  END IF;

  IF account_record.active = false
    AND (
      account_record.deactivated_at IS NULL
      OR NEW.captured_at_local > account_record.deactivated_at
    )
  THEN
    RAISE EXCEPTION 'Attendance captured after account deactivation is not accepted.';
  END IF;

  NEW.received_at_server = now();
  NEW.gps_expires_at = NEW.captured_at_local + interval '12 months';

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION snapshot_attendance_flag_workflow()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  flag_work_date date;
  selected_workflow text;
  selected_effective_from date;
BEGIN
  SELECT work_date
  INTO flag_work_date
  FROM public.attendance_sessions
  WHERE id = NEW.session_id
    AND user_id = NEW.user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Attendance flag must belong to its session owner.';
  END IF;

  IF NEW.attendance_event_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1
      FROM public.attendance_events
      WHERE id = NEW.attendance_event_id
        AND session_id = NEW.session_id
        AND user_id = NEW.user_id
    )
  THEN
    RAISE EXCEPTION 'Attendance flag event must belong to the same user and session.';
  END IF;

  SELECT
    rules.rule_value ->> NEW.flag_type::text,
    rules.effective_from
  INTO selected_workflow, selected_effective_from
  FROM public.attendance_rules AS rules
  WHERE rules.rule_key = 'flag_review_workflow_mode_by_flag_type'
    AND rules.effective_from <= flag_work_date
    AND (
      rules.effective_to IS NULL
      OR rules.effective_to >= flag_work_date
    )
  ORDER BY rules.effective_from DESC
  LIMIT 1;

  IF selected_workflow IS NULL
    OR selected_workflow NOT IN (
      'manager_review_admin_observe',
      'manager_preapprove_admin_final',
      'manager_view_admin_approve'
    )
  THEN
    RAISE EXCEPTION 'No valid flag review workflow is configured for flag type % on work date %.', NEW.flag_type, flag_work_date;
  END IF;

  NEW.workflow_mode = selected_workflow::flag_review_workflow_mode;
  NEW.workflow_effective_from = selected_effective_from;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION create_automatic_attendance_flags()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  account_record public.users%ROWTYPE;
  gps_threshold numeric;
  clock_threshold_minutes numeric;
BEGIN
  SELECT *
  INTO account_record
  FROM public.users
  WHERE id = NEW.user_id;

  IF account_record.active = false
    AND account_record.deactivated_at IS NOT NULL
    AND NEW.captured_at_local <= account_record.deactivated_at
  THEN
    INSERT INTO public.attendance_flags (
      session_id,
      attendance_event_id,
      user_id,
      flag_type,
      severity,
      evidence,
      workflow_mode,
      workflow_effective_from
    ) VALUES (
      NEW.session_id,
      NEW.id,
      NEW.user_id,
      'deactivated_user_record',
      'high',
      jsonb_build_object('deactivated_at', account_record.deactivated_at, 'captured_at_local', NEW.captured_at_local),
      'manager_review_admin_observe',
      CURRENT_DATE
    );
  END IF;

  IF NEW.event_type IN ('time_in', 'time_out', 'visit_in', 'visit_out')
    AND NEW.photo_path IS NULL
  THEN
    INSERT INTO public.attendance_flags (
      session_id,
      attendance_event_id,
      user_id,
      flag_type,
      severity,
      evidence,
      workflow_mode,
      workflow_effective_from
    ) VALUES (
      NEW.session_id,
      NEW.id,
      NEW.user_id,
      'missing_photo',
      'warning',
      jsonb_build_object('event_type', NEW.event_type),
      'manager_review_admin_observe',
      CURRENT_DATE
    );
  END IF;

  IF NEW.offline_declared THEN
    INSERT INTO public.attendance_flags (
      session_id,
      attendance_event_id,
      user_id,
      flag_type,
      severity,
      evidence,
      workflow_mode,
      workflow_effective_from
    ) VALUES (
      NEW.session_id,
      NEW.id,
      NEW.user_id,
      'offline_submission',
      'warning',
      NEW.offline_evidence || jsonb_build_object('received_at_server', NEW.received_at_server),
      'manager_view_admin_approve',
      CURRENT_DATE
    );

    IF NEW.received_at_server - NEW.captured_at_local > interval '24 hours' THEN
      INSERT INTO public.attendance_flags (
        session_id,
        attendance_event_id,
        user_id,
        flag_type,
        severity,
        evidence,
        workflow_mode,
        workflow_effective_from
      ) VALUES (
        NEW.session_id,
        NEW.id,
        NEW.user_id,
        'late_sync',
        'warning',
        jsonb_build_object(
          'delay_seconds', EXTRACT(EPOCH FROM NEW.received_at_server - NEW.captured_at_local),
          'received_at_server', NEW.received_at_server
        ),
        'manager_review_admin_observe',
        CURRENT_DATE
      );
    END IF;
  END IF;

  SELECT (rules.rule_value #>> '{}')::numeric
  INTO gps_threshold
  FROM public.attendance_rules AS rules
  JOIN public.attendance_sessions AS sessions
    ON sessions.id = NEW.session_id
  WHERE rules.rule_key = 'gps_low_accuracy_threshold_meters'
    AND rules.effective_from <= sessions.work_date
    AND (
      rules.effective_to IS NULL
      OR rules.effective_to >= sessions.work_date
    )
  ORDER BY rules.effective_from DESC
  LIMIT 1;

  IF NEW.gps_accuracy_meters IS NOT NULL
    AND gps_threshold IS NOT NULL
    AND NEW.gps_accuracy_meters > gps_threshold
  THEN
    INSERT INTO public.attendance_flags (
      session_id,
      attendance_event_id,
      user_id,
      flag_type,
      severity,
      evidence,
      workflow_mode,
      workflow_effective_from
    ) VALUES (
      NEW.session_id,
      NEW.id,
      NEW.user_id,
      'gps_low_accuracy',
      'warning',
      jsonb_build_object('gps_accuracy_meters', NEW.gps_accuracy_meters, 'threshold_meters', gps_threshold),
      'manager_review_admin_observe',
      CURRENT_DATE
    );
  END IF;

  SELECT (rules.rule_value #>> '{}')::numeric
  INTO clock_threshold_minutes
  FROM public.attendance_rules AS rules
  JOIN public.attendance_sessions AS sessions
    ON sessions.id = NEW.session_id
  WHERE rules.rule_key = 'clock_discrepancy_threshold_minutes'
    AND rules.effective_from <= sessions.work_date
    AND (
      rules.effective_to IS NULL
      OR rules.effective_to >= sessions.work_date
    )
  ORDER BY rules.effective_from DESC
  LIMIT 1;

  IF NEW.offline_declared = false
    AND clock_threshold_minutes IS NOT NULL
    AND abs(EXTRACT(EPOCH FROM NEW.received_at_server - NEW.captured_at_local))
      > clock_threshold_minutes * 60
  THEN
    INSERT INTO public.attendance_flags (
      session_id,
      attendance_event_id,
      user_id,
      flag_type,
      severity,
      evidence,
      workflow_mode,
      workflow_effective_from
    ) VALUES (
      NEW.session_id,
      NEW.id,
      NEW.user_id,
      'clock_discrepancy',
      'high',
      jsonb_build_object(
        'delta_seconds', abs(EXTRACT(EPOCH FROM NEW.received_at_server - NEW.captured_at_local)),
        'threshold_minutes', clock_threshold_minutes
      ),
      'manager_review_admin_observe',
      CURRENT_DATE
    );
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION validate_attendance_flag_review_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  flag_record public.attendance_flags%ROWTYPE;
  actor_role public.user_role;
  has_manager_access boolean;
BEGIN
  SELECT *
  INTO flag_record
  FROM public.attendance_flags
  WHERE id = NEW.attendance_flag_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Attendance flag review requires an existing attendance flag.';
  END IF;

  SELECT role
  INTO actor_role
  FROM public.users
  WHERE id = NEW.actor_user_id
    AND active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Attendance flag reviewer must be an active user.';
  END IF;

  IF auth.uid() IS NOT NULL AND NEW.actor_user_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'Attendance flag reviewer must match the current user.';
  END IF;

  IF NEW.stage = 'manager' THEN
    SELECT EXISTS (
      SELECT 1
      FROM public.manager_staff_assignments AS assignment
      WHERE assignment.manager_id = NEW.actor_user_id
        AND assignment.staff_user_id = flag_record.user_id
        AND assignment.effective_from <= CURRENT_DATE
        AND (
          assignment.effective_to IS NULL
          OR assignment.effective_to >= CURRENT_DATE
        )
      UNION ALL
      SELECT 1
      FROM public.manager_delegations AS delegation
      JOIN public.manager_delegation_capabilities AS capability
        ON capability.manager_delegation_id = delegation.id
       AND capability.capability = 'review_flags'
      JOIN public.manager_staff_assignments AS assignment
        ON assignment.manager_id = delegation.original_manager_id
       AND assignment.staff_user_id = flag_record.user_id
      WHERE delegation.covering_manager_id = NEW.actor_user_id
        AND delegation.revoked_at IS NULL
        AND delegation.effective_from <= CURRENT_DATE
        AND delegation.effective_to >= CURRENT_DATE
        AND assignment.effective_from <= CURRENT_DATE
        AND (
          assignment.effective_to IS NULL
          OR assignment.effective_to >= CURRENT_DATE
        )
    ) INTO has_manager_access;

    IF actor_role <> 'manager' OR NOT has_manager_access THEN
      RAISE EXCEPTION 'Manager flag review requires active review access to the affected staff member.';
    END IF;

    IF (flag_record.workflow_mode = 'manager_review_admin_observe'
        AND NEW.decision NOT IN ('approved', 'rejected', 'resolved'))
      OR (flag_record.workflow_mode = 'manager_preapprove_admin_final'
        AND NEW.decision NOT IN ('pre_approved', 'rejected'))
      OR flag_record.workflow_mode = 'manager_view_admin_approve'
    THEN
      RAISE EXCEPTION 'Manager review decision is incompatible with the flag workflow.';
    END IF;
  ELSE
    IF actor_role <> 'admin' THEN
      RAISE EXCEPTION 'Admin flag review requires an active admin.';
    END IF;

    IF flag_record.workflow_mode = 'manager_review_admin_observe'
      OR NEW.decision NOT IN ('approved', 'rejected', 'resolved')
    THEN
      RAISE EXCEPTION 'Admin review decision is incompatible with the flag workflow.';
    END IF;

    IF flag_record.workflow_mode = 'manager_preapprove_admin_final'
      AND NOT EXISTS (
        SELECT 1
        FROM public.attendance_flag_reviews
        WHERE attendance_flag_id = flag_record.id
          AND stage = 'manager'
          AND decision = 'pre_approved'
      )
    THEN
      RAISE EXCEPTION 'Admin final review requires an earlier manager pre-approval.';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION reject_attendance_event_mutation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  RAISE EXCEPTION 'Attendance events are immutable. Use correction workflows instead.';
END;
$$;

CREATE OR REPLACE FUNCTION reject_attendance_flag_mutation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  RAISE EXCEPTION 'Attendance flags are immutable. Record review outcomes in attendance_flag_reviews.';
END;
$$;

CREATE OR REPLACE FUNCTION reject_attendance_flag_review_mutation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  RAISE EXCEPTION 'Attendance flag reviews are append-only.';
END;
$$;

CREATE TRIGGER attendance_events_validate_insert
BEFORE INSERT ON attendance_events
FOR EACH ROW
EXECUTE FUNCTION validate_attendance_event_insert();

CREATE TRIGGER attendance_flags_snapshot_workflow
BEFORE INSERT ON attendance_flags
FOR EACH ROW
EXECUTE FUNCTION snapshot_attendance_flag_workflow();

CREATE TRIGGER attendance_events_create_automatic_flags
AFTER INSERT ON attendance_events
FOR EACH ROW
EXECUTE FUNCTION create_automatic_attendance_flags();

CREATE TRIGGER attendance_flag_reviews_validate_insert
BEFORE INSERT ON attendance_flag_reviews
FOR EACH ROW
EXECUTE FUNCTION validate_attendance_flag_review_insert();

CREATE TRIGGER attendance_events_reject_mutation
BEFORE UPDATE OR DELETE ON attendance_events
FOR EACH ROW
EXECUTE FUNCTION reject_attendance_event_mutation();

CREATE TRIGGER attendance_flags_reject_mutation
BEFORE UPDATE OR DELETE ON attendance_flags
FOR EACH ROW
EXECUTE FUNCTION reject_attendance_flag_mutation();

CREATE TRIGGER attendance_flag_reviews_reject_mutation
BEFORE UPDATE OR DELETE ON attendance_flag_reviews
FOR EACH ROW
EXECUTE FUNCTION reject_attendance_flag_review_mutation();

ALTER TABLE attendance_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_flags ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_flag_reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can select own attendance events"
ON attendance_events
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

CREATE POLICY "Managers can select direct or delegated team attendance events"
ON attendance_events
FOR SELECT
TO authenticated
USING (
  current_user_role() = 'manager'
  AND (
    EXISTS (
      SELECT 1
      FROM manager_staff_assignments
      WHERE manager_id = auth.uid()
        AND staff_user_id = attendance_events.user_id
        AND effective_from <= CURRENT_DATE
        AND (effective_to IS NULL OR effective_to >= CURRENT_DATE)
    )
    OR has_active_manager_delegation_for_staff(attendance_events.user_id, 'view_attendance')
    OR has_active_manager_delegation_for_staff(attendance_events.user_id, 'review_flags')
  )
);

CREATE POLICY "Admins can select all attendance events"
ON attendance_events
FOR SELECT
TO authenticated
USING (current_user_role() = 'admin');

CREATE POLICY "Users can select own attendance flags"
ON attendance_flags
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

CREATE POLICY "Managers can select direct or delegated team attendance flags"
ON attendance_flags
FOR SELECT
TO authenticated
USING (
  current_user_role() = 'manager'
  AND (
    EXISTS (
      SELECT 1
      FROM manager_staff_assignments
      WHERE manager_id = auth.uid()
        AND staff_user_id = attendance_flags.user_id
        AND effective_from <= CURRENT_DATE
        AND (effective_to IS NULL OR effective_to >= CURRENT_DATE)
    )
    OR has_active_manager_delegation_for_staff(attendance_flags.user_id, 'view_attendance')
    OR has_active_manager_delegation_for_staff(attendance_flags.user_id, 'review_flags')
  )
);

CREATE POLICY "Admins can select all attendance flags"
ON attendance_flags
FOR SELECT
TO authenticated
USING (current_user_role() = 'admin');

CREATE POLICY "Users can select reviews for own attendance flags"
ON attendance_flag_reviews
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM attendance_flags
    WHERE attendance_flags.id = attendance_flag_reviews.attendance_flag_id
      AND attendance_flags.user_id = auth.uid()
  )
);

CREATE POLICY "Managers can select reviews for direct or delegated team flags"
ON attendance_flag_reviews
FOR SELECT
TO authenticated
USING (
  current_user_role() = 'manager'
  AND EXISTS (
    SELECT 1
    FROM attendance_flags
    WHERE attendance_flags.id = attendance_flag_reviews.attendance_flag_id
      AND (
        EXISTS (
          SELECT 1
          FROM manager_staff_assignments
          WHERE manager_id = auth.uid()
            AND staff_user_id = attendance_flags.user_id
            AND effective_from <= CURRENT_DATE
            AND (effective_to IS NULL OR effective_to >= CURRENT_DATE)
        )
        OR has_active_manager_delegation_for_staff(attendance_flags.user_id, 'view_attendance')
        OR has_active_manager_delegation_for_staff(attendance_flags.user_id, 'review_flags')
      )
  )
);

CREATE POLICY "Admins can select all attendance flag reviews"
ON attendance_flag_reviews
FOR SELECT
TO authenticated
USING (current_user_role() = 'admin');

REVOKE INSERT, UPDATE, DELETE ON TABLE attendance_events FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE attendance_flags FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE attendance_flag_reviews FROM anon, authenticated;

REVOKE EXECUTE ON FUNCTION validate_attendance_event_insert() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION snapshot_attendance_flag_workflow() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION create_automatic_attendance_flags() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION validate_attendance_flag_review_insert() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION reject_attendance_event_mutation() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION reject_attendance_flag_mutation() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION reject_attendance_flag_review_mutation() FROM PUBLIC, anon, authenticated;
